import '@/styles/globals.css';

import { type Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/app/_components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={inter.className}
        suppressHydrationWarning
      >
        {children}
        <Toaster theme="light" />
      </body>
    </html>
  );
}
